import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import QuestCard from './QuestCard';
import FeedbackModal from './FeedbackModal';
import Leaderboard from './Leaderboard';
import { getXp, setXp as saveXp } from '../utils/xp';
import { auth } from '../firebase';
import { onAuthStateChanged } from 'firebase/auth';

export default function Dashboard() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [lastCompleted, setLastCompleted] = useState(null);
  const [xp, setXp] = useState(() => getXp() || 0);
  const [currentUser, setCurrentUser] = useState(null);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return () => unsubscribe();
  }, []);

  useEffect(() => {
    function onXpUpdated(e) {
      const newXp = (e && e.detail && typeof e.detail.xp === 'number') ? e.detail.xp : getXp();
      setXp(newXp);
    }
    function onXpCompleted(e) {
      const last = e && e.detail && e.detail.lastCompleted;
      if (last) {
        setLastCompleted(last);
        setOpen(true);
        setTimeout(() => setOpen(false), 2600);
      }
    }
    window.addEventListener('xpUpdated', onXpUpdated);
    window.addEventListener('xpCompleted', onXpCompleted);
    return () => {
      window.removeEventListener('xpUpdated', onXpUpdated);
      window.removeEventListener('xpCompleted', onXpCompleted);
    };
  }, []);

  // Updated quest completion handler
  function completeQuest({ title, xp: questXp, score }) {
    const totalXp = xp + (questXp || 0);
    setXp(totalXp);
    saveXp(totalXp);

    setLastCompleted(title);
    setOpen(true);
    setTimeout(() => setOpen(false), 2800);

    // Dispatch event for other components if needed
    window.dispatchEvent(new CustomEvent('xpUpdated', { detail: { xp: totalXp } }));
  }

  const quests = [
    {
      title: 'Mini Puzzle',
      desc: 'Solve a few quick puzzles generated by AI.',
      xp: 25,
      quizType: 'puzzle', // This tells QuestCard to launch a puzzle quiz
    },
    {
      title: 'Micro Project',
      desc: 'A mini-project scenario to test your knowledge.',
      xp: 50,
      quizType: 'project',
    },
    {
      title: 'Flash Learning',
      desc: 'Quick Q&A for a fast knowledge boost.',
      xp: 15,
      quizType: 'flash',
    },
  ];

  return (
    <div className="dashboard">
      <div className="header-row">
        <div style={{ display: 'flex', gap: 8, alignItems: 'center', justifyContent: 'flex-end', width: '100%' }}>
          <div className="feature-pill" style={{ cursor: 'pointer' }} onClick={() => navigate('/teacher-interaction')}>
            ✔ Cute AI teachers
          </div>
        </div>
      </div>

      <div className="left-panel">
        <div className="neon-card">
          <h3>🚀 Quests</h3>
          <p className="small-muted">Complete quests to earn XP and climb the leaderboard.</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: '20px' }}>
            {quests.map((q, i) => (
              <QuestCard
                key={i}
                title={q.title}
                desc={q.desc}
                xp={q.xp}
                quizType={q.quizType} // Pass the quiz type
                onComplete={completeQuest} // Use the updated handler
              />
            ))}
             <div onClick={() => navigate('/quests')} style={{ cursor: 'pointer' }}>
              <QuestCard title="More Quests" desc="Play a full quiz game and earn even more XP." onComplete={() => navigate('/quests')} />
            </div>
          </div>
        </div>

        <div className="neon-card glow">
          <h3>Core Idea</h3>
          <p className="small-muted">Embed learning into a story where AI NPCs create personalized quests, adapt difficulty, and give instant feedback.</p>
          <div style={{ marginTop: 12 }} className="grid-cards">
            <div className="neon-card" onClick={() => navigate('/teacher-types')} style={{ cursor: 'pointer' }}>
              <strong>AI NPC Teacher Types</strong>
              <p className="small-muted">Mentors, Story Guides, Code Coaches — each with cute reactions and tailored lessons.</p>
            </div>
            <div className="neon-card" onClick={() => navigate('/mentorship')} style={{ cursor: 'pointer' }}>
              <strong>1v1 Mentorship</strong>
              <p className="small-muted">Get guidance from two mentors at once.</p>
            </div>
            <div className="neon-card" onClick={() => navigate('/live-quiz')} style={{ cursor: 'pointer' }}>
              <strong>Live Quiz Game</strong>
              <p className="small-muted">Participate in a live quiz contest and see your name on the leaderboard.</p>
            </div>
            <div className="neon-card">
              <strong>Instant Feedback</strong>
              <p className="small-muted">Feedback with XP, sparkles, and emojis.</p>
            </div>
            <div className="neon-card">
              <strong>Emotional Gamification</strong>
              <p className="small-muted">Teachers empathize, celebrate wins, and adapt rewards.</p>
            </div>
          </div>
        </div>

        <div className="neon-card">
          <h3>Why this works</h3>
          <ul>
            <li>Short missions, dopamine hits</li>
            <li>Personalized — no boring repeating lessons</li>
            <li>Cute AI teachers feel like friends</li>
            <li>Instant progress visualization</li>
          </ul>
        </div>

        <Leaderboard currentUser={currentUser} />
      </div>

      <aside className="right-panel">
        <div className="neon-card">
          <h4>📊 Progress</h4>
           <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span className='small-muted'>Your XP</span>
              <span className='xp-display'>{xp} XP</span>
           </div>
          <div style={{ height: 10, background: 'rgba(255,255,255,0.04)', borderRadius: 8, overflow: 'hidden' }}>
            <div style={{ width: `${(xp/1000)*100}%`, height: 10, background: 'linear-gradient(90deg,var(--neon-1),var(--neon-2))' }} />
          </div>
          <div style={{ marginTop: 8 }} className="small-muted">Level up at 1000 XP</div>
        </div>

        <div className="neon-card">
          <h4>Quick Actions</h4>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            <button className="btn primary" onClick={() => navigate('/teacher-interaction')}>Chat with AI Mentor</button>
            <button className="btn ghost" onClick={() => navigate('/analytics')}>View Analytics</button>
          </div>
        </div>
      </aside>

      <FeedbackModal open={open} onClose={() => setOpen(false)} title={lastCompleted ? `Completed: ${lastCompleted}` : 'Nice job!'} message={'You earned XP and a little celebration ✨'} />
    </div>
  );
}
