import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import QuestCard from './QuestCard';
import FeedbackModal from './FeedbackModal';
import Leaderboard from './Leaderboard';
import { getXp, setXp as saveXp } from '../utils/xp';
import { auth } from '../firebase';
import { onAuthStateChanged } from 'firebase/auth';

export default function Dashboard() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const [lastCompleted, setLastCompleted] = useState(null);
  const [xp, setXp] = useState(() => getXp() || 0);
  const [currentUser, setCurrentUser] = useState(null);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return () => unsubscribe();
  }, []);

  // Updated quest completion handler
  function completeQuest({ title, xp: questXp, score }) {
    const totalXp = xp + (questXp || 0);
    setXp(totalXp);
    saveXp(totalXp);

    setLastCompleted(title);
    setOpen(true);
    setTimeout(() => setOpen(false), 2800);

    // Dispatch event for other components if needed
    window.dispatchEvent(new CustomEvent('xpUpdated', { detail: { xp: totalXp } }));
  }

  const quests = [
    {
      title: 'Mini Puzzle',
      desc: 'Solve a few quick puzzles generated by AI.',
      xp: 25,
      quizType: 'puzzle', // This tells QuestCard to launch a puzzle quiz
    },
    {
      title: 'Micro Project',
      desc: 'A mini-project scenario to test your knowledge.',
      xp: 50,
      quizType: 'project',
    },
    {
      title: 'Flash Learning',
      desc: 'Quick Q&A for a fast knowledge boost.',
      xp: 15,
      quizType: 'flash',
    },
  ];

  return (
    <div className="dashboard">
      <div className="left-panel">
        <div className="neon-card">
          <h3>🚀 Quests</h3>
          <p className="small-muted">Complete quests to earn XP and climb the leaderboard.</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: '20px' }}>
            {quests.map((q, i) => (
              <QuestCard
                key={i}
                title={q.title}
                desc={q.desc}
                xp={q.xp}
                quizType={q.quizType} // Pass the quiz type
                onComplete={completeQuest} // Use the updated handler
              />
            ))}
             <div onClick={() => navigate('/quests')} style={{ cursor: 'pointer' }}>
              <QuestCard title="More Quests" desc="Play a full quiz game and earn even more XP." onComplete={() => navigate('/quests')} />
            </div>
          </div>
        </div>

        <Leaderboard currentUser={currentUser} />
      </div>

      <aside className="right-panel">
        <div className="neon-card">
          <h4>📊 Progress</h4>
           <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span className='small-muted'>Your XP</span>
              <span className='xp-display'>{xp} XP</span>
           </div>
          <div style={{ height: 10, background: 'rgba(255,255,255,0.04)', borderRadius: 8, overflow: 'hidden' }}>
            <div style={{ width: `${(xp/1000)*100}%`, height: 10, background: 'linear-gradient(90deg,var(--neon-1),var(--neon-2))' }} />
          </div>
          <div style={{ marginTop: 8 }} className="small-muted">Level up at 1000 XP</div>
        </div>

        <div className="neon-card">
          <h4>Quick Actions</h4>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            <button className="btn primary" onClick={() => navigate('/teacher-interaction')}>Chat with AI Mentor</button>
            <button className="btn ghost" onClick={() => navigate('/analytics')}>View Analytics</button>
          </div>
        </div>
      </aside>

      <FeedbackModal open={open} onClose={() => setOpen(false)} title={lastCompleted ? `Completed: ${lastCompleted}` : 'Nice job!'} message={'You earned XP and a little celebration ✨'} />
    </div>
  );
}
